#!/usr/bin/env python3
# coding: utf-8

"""Script to implement a shell to talk to a Sieve server using sievelib."""

# BSD Zero Clause License
#
# Copyright (c) 2020,2026 Scott A. Anderson
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

# Possible enhancements:
# Completions (complete_*) for the do_* commands.
# Print out warnings from a putscript that returns OK and in general,
#  revisit the handling of server responses because RFC 5804 says that
#  "implementations MUST NOT attempt to parse the message for meaning."
# Command to allow debug to be turned on, off and perhaps responses only.
# Command or option to write a skeleton ~/.sieveshrc file.

import argparse
import cmd
import configparser
import fnmatch
import getpass
import hashlib
import os
import readline
import shlex
import shutil
import sys

from sievelib.managesieve import Client, Error

def multicolumn_print(str_list):
    """Prints out a the strings in strlist à la the ls multicolumn output

    If str_list is None, nothing will be printed.  Otherwise the strings in
    str_list will be printed to stdout in top to bottom, left to right
    columns taking the terminal's width into account.

    :param str_list: The list of strings to print.
    """
    if not str_list:
        return
    term_width, _term_height = shutil.get_terminal_size()
    max_item_len = len(max(str_list, key=len))
    col_len = (int((max_item_len + 1) / 8) + 1) * 8
    num_cols = int((term_width + 1) / col_len)
    num_rows = int((len(str_list) + num_cols - 1) / num_cols)
    for row in range(num_rows):
        line = ''
        for col in range(num_cols):
            list_index = col * num_rows + row
            if list_index < len(str_list):
                item = str_list[list_index]
                line += item
                if col < num_cols - 1:
                    tab_len = col_len - (int(len(item) / 8) * 8)
                    line += (int(tab_len / 8)) * '\t'
        print(line)


def glob_match(sources, globs, source_type='script'):
    """Returns a list of the sources that match any of the globs

    If globs is None, sources will be returned as is.  Otherwise, a list is
    returned that contains all sources that match any of the globs.  If a
    glob doesn't match any patterns, an error telling the user will be
    printed on stderr.

    :param sources: The list of sources to match against the globs.
    :param globs: The list of glob patterns to match.

    :returns: a list of the sources that match any of the globs.
    """
    if not globs:
        return sources

    matches = []
    for glob_str in globs:
        this_match = [s for s in sources if fnmatch.fnmatch(s, glob_str)]
        if this_match:
            matches += sorted(this_match)
        else:
            print(f'{glob_str}: No such {source_type}', file=sys.stderr)
    return matches


def process_script_globs(server_scripts, globs, sort=False):
    """Returns a list of the server_scripts that match any of the globs.

    :param server_scripts: Scripts on server as returned by Client.listscripts()
    :param globs: A list of the glob patterns to match.
    :param sort: Iff true, the returned list will be sorted.
    :rtype: list
    :return: The scripts that match.
    """
    active = server_scripts[0]
    server_scripts = server_scripts[1]
    if active:
        server_scripts = [active] + server_scripts
    matched_scripts = glob_match(server_scripts, globs)
    if sort:
        return sorted(matched_scripts)
    return matched_scripts


class ArgumentParser(argparse.ArgumentParser):
    """Subclass of ArgumentParser that raises ValueError instead of exiting."""
    def exit(self, status=0, message=None):
        """Raise an assertion instead of exiting when ArgumentParser exits.

        If message is not None, it will be printed to stderr.  ValueError
        will then be raised with message as its parameter.

        Args:
            status: The status that is normally passed to exit().  Ignored.
            message: String to be printed and used to initialize ValueError.

        Raises:
            ValueError: The argument parser is exiting.
        """

        del status  # unused
        if message:
            self._print_message(message, sys.stderr)
        raise ValueError(message)

class SieveCmd(cmd.Cmd):
    """Subclass of Cmd to implement the shell."""
    def __init__(self, sieve_client):
        readline.set_completer_delims(' \t\n')
        super().__init__()
        self.sieve_client = sieve_client
        self.doc_header = 'Commands (type help <topic>):'
        self.misc_header = 'Other help topics:'
        self.ruler = ''
        self.prompt = '> '

    def cmdloop_catches_keyboard_interrupt(self):
        """Wrapper around cmdloop() that politely handles keyboard interrupts"""
        running = True
        while running:
            try:
                self.cmdloop()
                running = False  # cmdloop returned; we should exit
            except KeyboardInterrupt:
                print()

    def emptyline(self):
        return False

    # shell '!' command
    @staticmethod
    def do_shell(line):
        """Implements the '!' (shell) command

        This command passes the remainder of the command line to os.system().

        :param line: The user's command with the command name removed.
        :rtype: boolean
        :return: Always False indicating the command processor should not exit.
        """
        os.system(line)
        return False
    @staticmethod
    def help_shell():
        """Implements help for the '!' (shell) command"""
        print('usage: shell|! command')
        print()
        print('Execute shell command')

    # comment '_' command
    @staticmethod
    def do__(line):
        """Implements the '_' (comment) command

        This command ignores all parameters.

        :param line: The user's command with the command name removed.
        :rtype: boolean
        :return: Always False indicating the command processor should not exit.
        """
        # Ignore anything on this 'comment' line
        del line  # unused
        return False
    @staticmethod
    def help__():
        """Implements help for the '_' (comment) command"""
        print('usage: _ comments')
        print()
        print('Enter comments')

    # logout, quit, exit and EOF commands
    parse_logout = ArgumentParser(
        prog='logout|exit|quit|EOF',
        description='Logout from Sieve server and exit.')
    help_logout = parse_logout.print_help
    def do_logout(self, line):
        """Implements the logout, exit, quit and EOF commands

        The logout, exit and quit commands all do the same thing as
        pressing ^D to indicate an EOF: they logout from the Sieve server,
        disconnect the socket and exit the program.

        :param line: The user's command with the command name removed.
        :rtype: boolean
        :return: True if no error indicating the command processor should exit.
        """
        try:
            _args = self.parse_logout.parse_args(shlex.split(line))
        except ValueError:
            return False

        self.sieve_client.logout()
        del self.sieve_client
        if not self.lastcmd:
            print()
        return True
    help_exit = parse_logout.print_help
    do_exit = do_logout
    help_quit = parse_logout.print_help
    do_quit = do_logout
    help_EOF = parse_logout.print_help
    do_EOF = do_logout

    # caps command
    parse_caps = ArgumentParser(
        prog='caps',
        description='List Sieve server capabilites.',
        epilog='The CAPABILITY arguments are glob expanded.')
    parse_caps.add_argument('--command-only', dest='only',
                            action='store_const', const='command',
                            help='Show only capabilites returned by command')
    parse_caps.add_argument('--connect-only', dest='only',
                            action='store_const', const='connect',
                            help='Show only capabilites returned by connect')
    parse_caps.add_argument('-1', dest='fmt', action='store_const', const='1',
                            help='(The digit "one".) Single column output')
    parse_caps.add_argument('-C', dest='fmt', action='store_const', const='C',
                            help='Multiple column output (the default)')
    parse_caps.add_argument('globs', metavar='CAPABILITY', nargs='*',
                            help='Only display given CAPABILITY(s)')
    help_caps = parse_caps.print_help
    def do_caps(self, line):
        """Implements the caps command

        The caps command lists the Sieve capabilities that the server has.
        If CAPABILITYs are specified, only capabilities that match those
        glob patterns will be listed.  Note that some servers do not
        provide the same list of capabilites in response to the connection
        being made and to the CAPABILITY command.  By default, caps will
        show all the capabilities that either mechanism provide.  The
        --command-only and --connect-only options can be used to list
        capabilities that were provide by just one or the other.

        :param line: The user's command with the command name removed.
        :rtype: boolean
        :return: Always False indicating the command processor should not exit.
        """
        try:
            args = self.parse_caps.parse_args(shlex.split(line))
        except ValueError:
            return False

        caps_from_connect = set(self.sieve_client.get_sieve_capabilities())

        caps_from_command = set()
        for cape in self.sieve_client.capability().splitlines():
            key, val = cape.split(maxsplit=1)
            if key == b'"SIEVE"':
                val = [c.decode('utf-8').strip('"') for c in val.split()]
                caps_from_command = set(val)
                break

        if args.only == 'command':
            caps = caps_from_command - caps_from_connect
        elif args.only == 'connect':
            caps = caps_from_connect - caps_from_command
        else:
            caps = caps_from_command.intersection(caps_from_connect)

        caps = sorted(glob_match(caps, args.globs, source_type='capability'))

        if args.fmt == '1':
            for cap in caps:
                print(cap)
        else:
            multicolumn_print(caps)

        return False

    # ls command
    parse_ls = ArgumentParser(
        prog='ls',
        description='List scripts present on Sieve server.',
        epilog='The SCRIPT arguments are glob expanded.')
    parse_ls.add_argument('-1', dest='fmt', action='store_const', const='1',
                          help='(The digit "one".) Single column output')
    parse_ls.add_argument('-C', dest='fmt', action='store_const', const='C',
                          help='Multiple column output (the default)')
    parse_ls.add_argument('-F', '--classify', action='store_true',
                          help="Append an asterisk to active script's name")
    parse_ls.add_argument('-f', dest='sort', action='store_false',
                          help='Do not sort the output')
    parse_ls.add_argument('-l', dest='fmt', action='store_const', const='l',
                          help='Output one line per script with size and name')
    parse_ls.add_argument('globs', metavar='SCRIPT', nargs='*',
                          help='Only display the given SCRIPTs')
    help_ls = parse_ls.print_help
    def do_ls(self, line):
        """Implements the ls command

        The ls command lists the scripts that are on the Sieve server.  If
        SCRIPTs are specified, only scripts that match those glob patterns
        will be listed.  Note that if the '-l' option is used, do_ls will
        temporarily download each matched script into memory in order to
        determine the size.

        :param line: The user's command with the command name removed.
        :rtype: boolean
        :return: Always False indicating the command processor should not exit.
        """
        try:
            args = self.parse_ls.parse_args(shlex.split(line))
        except ValueError:
            return False

        server_scripts = self.sieve_client.listscripts()
        active = server_scripts[0]
        scripts = process_script_globs(server_scripts, args.globs,
                                       sort=args.sort)

        if args.fmt == '1':
            for script in scripts:
                if args.classify and script == active:
                    script += '*'
                print(script)
        elif args.fmt == 'l':
            for script in scripts:
                size = len(self.sieve_client.getscript(script))
                if args.classify and script == active:
                    script += '*'
                print(f'{size:8} {script}')
        else:
            if args.classify:
                scripts = [s + '*' if s == active else s for s in scripts]
            multicolumn_print(scripts)

        return False

    # hashsum command
    parse_hashsum = ArgumentParser(
        prog='hashsum',
        description='Calculate hashes of Sieve server scripts.',
        epilog='The SCRIPT arguments are glob expanded.')
    parse_hashsum.add_argument('-a', '--algorithm', default='md5',
                               choices=sorted(hashlib.algorithms_available),
                               help='The hash algorithm to use (default=md5)')
    parse_hashsum.add_argument('globs', metavar='SCRIPT', nargs='*',
                               help='Only display the given SCRIPTs')
    help_hashsum = parse_hashsum.print_help
    def do_hashsum(self, line):
        """Implements the hashsum command

        The hashsum command lists hashes of scripts on the Sieve server.
        Note each script will be downloaded into memory to determine the
        hash.

        :param line: The user's command with the command name removed.
        :rtype: boolean
        :return: Always False indicating the command processor should not exit.
        """
        try:
            args = self.parse_hashsum.parse_args(shlex.split(line))
        except ValueError:
            return False

        scripts = process_script_globs(self.sieve_client.listscripts(),
                                       args.globs)

        for script in scripts:
            content = self.sieve_client.getscript(script)
            hsh = hashlib.new(args.algorithm)
            hsh.update(bytes(content, 'utf-8'))
            hexdigest = hsh.hexdigest()
            print(f'{hexdigest}  {script}')

        return False

    # rm command
    parse_rm = ArgumentParser(
        prog='rm',
        description="Remove one or more scripts.",
        epilog='The SCRIPT arguments are glob expanded.')
    parse_rm.add_argument('-v', '--verbose', action='store_true',
                          help='Print names of scripts as they are deleted')
    parse_rm.add_argument('globs', metavar='SCRIPT', nargs='*',
                          help='Script(s) to remove.')
    help_rm = parse_rm.print_help
    def do_rm(self, line):
        """Implements the rm command

        The rm command allows the user to remove scripts from the server.
        For convenience, globbing is done on the user input.

        :param line: The user's command with the command name removed.
        :rtype: boolean
        :return: Always False indicating the command processor should not exit.
        """
        try:
            args = self.parse_rm.parse_args(shlex.split(line))
        except ValueError:
            return False

        scripts = process_script_globs(self.sieve_client.listscripts(),
                                       args.globs)

        for script in scripts:
            if not self.sieve_client.deletescript(script):
                errmsg = self.sieve_client.error[1].decode()
                print(f'{script}: {errmsg}', file=sys.stderr)
            elif args.verbose:
                print(script)

        return False

    # mv command
    parse_mv = ArgumentParser(
        prog='mv',
        description="Move a script to a new name.",
        epilog='The SOURCE argument is glob expanded.')
    parse_mv.add_argument('-A', '--activate', action='store_true',
                          help='Make destination the active script')
    parse_mv.add_argument('-v', '--verbose', action='store_true',
                          help='Print action taken')
    parse_mv.add_argument('SOURCE', help='Source script name')
    parse_mv.add_argument('DESTINATION', help='Destination script name')
    help_mv = parse_mv.print_help
    def do_mv(self, line):
        """Implements the mv command

        The mv command allows the user to move a script on the server to a
        new name.  For convenience, globbing is done on the SOURCE, however
        after globbing there may be only one source.

        :param line: The user's command with the command name removed.
        :rtype: boolean
        :return: Always False indicating the command processor should not exit.
        """
        try:
            args = self.parse_mv.parse_args(shlex.split(line))
        except ValueError:
            return False

        src = process_script_globs(self.sieve_client.listscripts(),
                                   [args.SOURCE])
        if len(src) != 1:
            SieveCmd.parse_mv.print_usage(file=sys.stderr)
            return False
        src = src[0]
        dst = args.DESTINATION

        if not self.sieve_client.renamescript(src, dst):
            errmsg = self.sieve_client.error[1].decode()
            print(f'Could not move {src!r} to {dst!r}: {errmsg}',
                  file=sys.stderr)
        elif args.verbose:
            print(f'{src} -> {dst}')

        if args.activate:
            if not self.sieve_client.setactive(dst):
                errmsg = self.sieve_client.error[1].decode()
                print(f'{dst}: Could not be made active: {errmsg}',
                      file=sys.stderr)
            elif args.verbose:
                print(f'{dst} now active.')

        return False

    # cp command
    parse_cp = ArgumentParser(
        prog='cp',
        description="Copy a script to a new script.",
        epilog='The SOURCE argument is glob expanded.')
    parse_cp.add_argument('-A', '--activate', action='store_true',
                          help='Make destination the active script')
    parse_cp.add_argument('-v', '--verbose', action='store_true',
                          help='Print action taken')
    parse_cp.add_argument('SOURCE', help='Source script name')
    parse_cp.add_argument('DESTINATION', help='Destination script name')
    help_cp = parse_cp.print_help
    def do_cp(self, line):
        """Implements the cp command

        The cp command allows the user to copy a script on the server to a
        new script.  For convenience, globbing is done on the SOURCE,
        however after globbing there may be only one source.

        :param line: The user's command with the command name removed.
        :rtype: boolean
        :return: Always False indicating the command processor should not exit.
        """
        try:
            args = self.parse_cp.parse_args(shlex.split(line))
        except ValueError:
            return False

        src = process_script_globs(self.sieve_client.listscripts(),
                                   [args.SOURCE])
        if len(src) != 1:
            SieveCmd.parse_cp.print_usage(file=sys.stderr)
            return False
        src = src[0]
        dst = args.DESTINATION

        content = self.sieve_client.getscript(src)
        if not content:
            errmsg = self.sieve_client.error[1].decode()
            print(f'Could not get {src!r} script: {errmsg}', file=sys.stderr)
            return False

        if not self.sieve_client.havespace(dst, len(content)):
            errmsg = self.sieve_client.error[1].decode()
            print(f'Not enough space for {dst!r}: {errmsg}', file=sys.stderr)
            return False

        if not self.sieve_client.putscript(dst, content):
            errmsg = self.sieve_client.error[1].decode()
            print(f'Could not put {dst!r} script:\n{errmsg}', file=sys.stderr)
        elif args.verbose:
            print(f'{src} -> {dst}')

        if args.activate:
            if not self.sieve_client.setactive(dst):
                errmsg = self.sieve_client.error[1].decode()
                print(f'{dst}: Could not be made active: {errmsg}',
                      file=sys.stderr)
            elif args.verbose:
                print(f'{dst} now active.')

        return False

    # get command
    parse_get = ArgumentParser(
        prog='get',
        description="Make a local copy of a Sieve server script.",
        epilog='The SCRIPT argument is glob expanded.  If FILE is not '
               'given, it defaults to appending ".siv" to the SCRIPT name.')
    parse_get.add_argument('-v', '--verbose', action='store_true',
                           help='Print action taken')
    parse_get.add_argument('SCRIPT', help='Source script name')
    parse_get.add_argument('FILE', help='Destination file name', nargs='?')
    help_get = parse_get.print_help
    def do_get(self, line):
        """Implements the get command

        The get command allows the user to copy a script on the server to a
        local file.  For convenience, globbing is done on the SCRIPT,
        however after globbing there may be only one script.

        :param line: The user's command with the command name removed.
        :rtype: boolean
        :return: Always False indicating the command processor should not exit.
        """
        try:
            args = self.parse_get.parse_args(shlex.split(line))
        except ValueError:
            return False

        src = process_script_globs(self.sieve_client.listscripts(),
                                   [args.SCRIPT])
        if len(src) != 1:
            SieveCmd.parse_get.print_usage(file=sys.stderr)
            return False
        src = src[0]
        dst = args.FILE
        if not dst:
            dst = src + '.siv'

        content = self.sieve_client.getscript(src)
        if not content:
            errmsg = self.sieve_client.error[1].decode()
            print(f'Could not get {src!r} script: {errmsg}', file=sys.stderr)
            return False

        try:
            with open(dst, 'w', encoding='utf-8') as file:
                file.write(content)
        except OSError as err:
            print(f'{dst}: {err}', file=sys.stderr)
            return False

        print(f'Sieve server script {src!r} copied to file {dst!r}.')

        return False

    # put command
    parse_put = ArgumentParser(
        prog='put',
        description="Copy a local file to a Sieve server script.",
        epilog='If the SCRIPT argument is not given, it defaults to '
               'the FILE name after removing a ".siv" suffix if present.')
    parse_put.add_argument('-A', '--activate', action='store_true',
                           help='Make destination the active script')
    parse_put.add_argument('-v', '--verbose', action='store_true',
                           help='Print action taken')
    parse_put.add_argument('FILE', help='Source file name')
    parse_put.add_argument('SCRIPT', help='Destination script name', nargs='?')
    help_put = parse_put.print_help
    def do_put(self, line):
        """Implements the put command

        The put command allows the user to copy a local file to a script on
        the server.

        :param line: The user's command with the command name removed.
        :rtype: boolean
        :return: Always False indicating the command processor should not exit.
        """
        try:
            args = self.parse_put.parse_args(shlex.split(line))
        except ValueError:
            return False

        src = args.FILE
        dst = args.SCRIPT
        if not dst:
            dst = os.path.basename(src)
            dst_name, dst_ext = os.path.splitext(dst)
            if dst_ext == '.siv':
                dst = dst_name

        content = ''
        try:
            with open(src, 'r', encoding='utf-8') as file:
                content += file.read()
        except OSError as err:
            print(f'{dst}: {err}', file=sys.stderr)
            return False

        if not self.sieve_client.havespace(dst, len(content)):
            errmsg = self.sieve_client.error[1].decode()
            print(f'There is not space for {dst!r}: {errmsg}', file=sys.stderr)
            return False

        if not self.sieve_client.checkscript(content):
            errmsg = self.sieve_client.error[1].decode()
            print(f'Error in {src!r} script: {errmsg}', file=sys.stderr)
            return False

        if not self.sieve_client.putscript(dst, content):
            errmsg = self.sieve_client.error[1].decode()
            print(f'Could not put {dst!r} script:\n{errmsg}', file=sys.stderr)
        elif args.verbose:
            print(f'File {src!r} copied to Sieve server script {dst!r}.')

        if args.activate:
            if not self.sieve_client.setactive(dst):
                errmsg = self.sieve_client.error[1].decode()
                print(f'{dst}: Could not be made active: {errmsg}',
                      file=sys.stderr)
            elif args.verbose:
                print(f'{dst} now active.')

        return False

    # pact command
    parse_pact = ArgumentParser(
        prog='pact',
        description='Print name of active script.')
    help_pact = parse_pact.print_help
    def do_pact(self, line):
        """Implements the pact command

        The pact command prints the name of the active script.  If no
        script is active, nothing will be printed.

        :param line: The user's command with the command name removed.
        :rtype: boolean
        :return: Always False indicating the command processor should not exit.
        """
        try:
            _args = self.parse_pact.parse_args(shlex.split(line))
        except ValueError:
            return False

        scripts = self.sieve_client.listscripts()
        active = scripts[0]
        if active:
            print(active)

        return False

    # cact command
    parse_cact = ArgumentParser(
        prog='cact',
        description="Change active script.  Pass '' to inactivate all scripts.",
        epilog='The SCRIPT argument is glob expanded.')
    parse_cact.add_argument('-v', '--verbose', action='store_true',
                            help='Print name of script made active.')
    parse_cact.add_argument('globs', metavar='SCRIPT', nargs=1,
                            help='Script to make active.')
    help_cact = parse_cact.print_help
    def do_cact(self, line):
        """Implements the cact command

        The cact command allows the user to change the active script to the
        one specified or to inactivate all scripts by passing ''.  For
        convenience, globbing is done on the user input.

        :param line: The user's command with the command name removed.
        :rtype: boolean
        :return: Always False indicating the command processor should not exit.
        """
        try:
            args = self.parse_cact.parse_args(shlex.split(line))
        except ValueError:
            return False

        script = args.globs[0]
        if script != '':
            scripts = process_script_globs(self.sieve_client.listscripts(),
                                           args.globs)
            if len(scripts) != 1:
                print(f'cact: {scripts}: Only one script may be made active.')
                SieveCmd.parse_cact.print_usage(file=sys.stderr)
                return False
            script = scripts[0]

        if not self.sieve_client.setactive(script):
            errmsg = self.sieve_client.error[1].decode()
            print(f'{script}: Could not be made active: {errmsg}',
                  file=sys.stderr)
        elif args.verbose:
            print(f'{script}')

        return False


def main():
    """main() for sievesh.py

    Parse the command line arguments, connect to the Sieve server and then
    start processing commands from the user.

    :rtype: int
    :returns: exit status (currently always zero)
    """
    argp = argparse.ArgumentParser(description=__doc__)
    argp.add_argument('-F', '--config-file',
                      default=os.path.expanduser('~/.sieveshrc'),
                      help="The configuration file to use.")
    argp.add_argument('-c', '--config-section', default='DEFAULT',
                      help="The section of the configuration file to use.")
    argp.add_argument('--host',
                      help="The Sieve server host to connect to.")
    argp.add_argument('--port',
                      help="The port to connect to on the server.")
    argp.add_argument('--user',
                      help='The user to connect as.')
    argp.add_argument('--password',
                      help='The password will be prompted for if not given.')
    argp.add_argument('-d', '--debug', action='store_true',
                      help='Show interactions with the Sieve server.')
    argp.add_argument('-v', '--verbose', action='store_true',
                      help='Show connection information.')
    args = argp.parse_args()

    cfgp = configparser.ConfigParser()
    cfgp.read(args.config_file)
    cfg = cfgp[args.config_section]

    host = args.host if args.host else cfg.get('host')
    port = args.port if args.port else cfg.getint('port', 4190)
    user = args.user if args.user else cfg.get('user')
    password = args.password if args.password else cfg.get('password')

    missing_ci = False
    if not host:
        print('The host to connect to was not provided.', file=sys.stderr)
        missing_ci = True
    if not port:
        print('The port to connect to was not provided.', file=sys.stderr)
        missing_ci = True
    if not user:
        print('The user to connect as was not provided.', file=sys.stderr)
        missing_ci = True
    if missing_ci:
        argp.print_usage(file=sys.stderr)
        return 2

    if args.verbose:
        print(f'Connecting to port {port!r} on {host!r} as user {user!r}')

    if not password:
        password = getpass.getpass()

    try:
        sieve_client = Client(host, port, debug=args.debug)
        sieve_client.connect(user, password, starttls=True)
    except Error as err:
        print(f'Could not connect: {err}', file=sys.stderr)
        return 1

    sievecmd = SieveCmd(sieve_client)
    sievecmd.cmdloop_catches_keyboard_interrupt()
    return 0

if __name__ == "__main__":
    sys.exit(main())
